FootascrazyCarSales/Models/Car/CarListingVm.cs
using FootascrazyCarSales.Application.Dto.Car;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FootascrazyCarSales.Models.Car
{
    public class CarListingVm
    {
        public IList<CarDto> Listings { get; set; }
    }
}

FootascrazyCarSales/Models/Car/CarVm.cs
using FootascrazyCarSales.Application.Dto.Car;
using FootascrazyCarSales.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace FootascrazyCarSales.Models.Car
{
    public class CarVm
    {
        public CarDto Entity { get; set; }

        #region UI Logic
        public bool DisplayEgcPrice()
        {
            return Entity.PriceType == PriceType.ExcludingGovtCharges;
        }

        public bool DisplayDapPrice()
        {
            return Entity.PriceType == PriceType.DriveAwayPrice;
        }

        /// <summary>
        /// Contact details are only displayed during private sales
        /// </summary>
        public bool DisplayPrivateSaleDetails()
        {
            /// TODO J Clarify business requirement around how private sale
            /// is determined in absence of specific flag. For now this will do.
            return (Entity.PriceType == PriceType.PriceOnApplication);
        }

        /// <summary>
        /// The price displayed is determined by the priceType attribute of CarDto
        /// </summary>
        /// <returns>Price and affix which indicates the price type</returns>
        public String DisplayRelevantPrice()
        {
            StringBuilder relevantPrice = new StringBuilder();

            switch (Entity.PriceType)
            {
                case PriceType.DriveAwayPrice:
                    relevantPrice.Append(Entity.DapPrice); 
                    relevantPrice.Append(" - Drive Away Price");
                    break;

                case PriceType.ExcludingGovtCharges:
                    relevantPrice.Append(Entity.EgcPrice);
                    relevantPrice.Append(" - Excluding Govt. Charges");
                    break;
            }

            return relevantPrice.ToString();
        }
        #endregion
    }
}

FootascrazyCarSales/Models/Enquiry/EnquiryVm.cs
using FootascrazyCarSales.Application.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FootascrazyCarSales.Models.Enquiry
{
    public class EnquiryVm
    {
        public EnquiryDto Entity { get; set; }
    }
}

FootascrazyCarSales/Controllers/CarController.cs
using FootascrazyCarSales.Application.Service.Car;
using FootascrazyCarSales.Models.Car;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FootascrazyCarSales.Controllers
{
    public class CarController : Controller
    {
        //
        // GET: /Car/

        public ActionResult List()
        {
            CarService service = new CarService();
            CarListingVm carListingVm = new CarListingVm();
            carListingVm.Listings = service.List();
            return View(carListingVm);
        }

        public ActionResult Detail(long id)
        {
            CarService service = new CarService(); 
            CarVm carVm = new CarVm();
            carVm.Entity = service.FindById(id);

            return View(carVm);
        }

    }
}

FootascrazyCarSales/Controllers/EnquiryController.cs
using FootascrazyCarSales.Application.Dto;
using FootascrazyCarSales.Application.Service.Enquiry;
using FootascrazyCarSales.Models.Enquiry;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FootascrazyCarSales.Controllers
{
    public class EnquiryController : Controller
    {
        //
        // GET: /Enquiry/

        public ActionResult Create(long id)
        {
            EnquiryVm model = new EnquiryVm() { Entity = new EnquiryDto() { CarId = id } };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(EnquiryVm model)
        {
            if (!ModelState.IsValid)
                return View();

            EnquiryService service = new EnquiryService();
            service.Enquire(model.Entity);

            return View("EnquirySubmitted", model);
        }

    }
}

FootascrazyCarSales/Views/Car/Detail.cshtml
@model FootascrazyCarSales.Models.Car.CarVm

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Entity.Name, @Model.Entity.Description</h2>

<table>
    <tr>
        <td>Make</td>
        <td>@Model.Entity.Make</td>
    </tr>
    <tr>
        <td>Model</td>
        <td>@Model.Entity.Model</td>
    </tr>
    <tr>
        <td>Year</td>
        <td>@Model.Entity.Year</td>
    </tr>
    <tr>
        <td>Price</td>
        <td>@Model.DisplayRelevantPrice()</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>@Model.Entity.Email</td>
    </tr>
    @if(Model.DisplayPrivateSaleDetails()){
        <tr>
            <td>Phone</td>
            <td></td>
        </tr>
        <tr>
            <td>Contact Name</td>
            <td></td>
        </tr>
    } else {
        <tr>
            <td>Dealer ABN</td>
            <td>@Model.Entity.DealerAbn</td>
        </tr>
    }
    <tr>
        <td>Comments</td>
        <td>@Model.Entity.Comments</td>
    </tr>
</table>

@{Html.RenderAction("Create", "Enquiry", new { id = Model.Entity.Id });}

FootascrazyCarSales/Views/Car/List.cshtml
@using FootascrazyCarSales.Application.Dto.Car

@model FootascrazyCarSales.Models.Car.CarListingVm

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cars</h2>

<table>
    <thead>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        <th>More Details</th>
    </thead>
    <tbody>
    @{
        foreach (CarDto carDto in Model.Listings)
        {
            <tr>
                <td>@carDto.Make</td>
                <td>@carDto.Model</td>
                <td>@carDto.Year</td>
                <td><a href="@Url.Action("Detail", "Car", new { @id = carDto.Id })">View</a></td>
            </tr>
        }   
    }
    </tbody>
</table>

FootascrazyCarSales/Views/Enquiry/Create.cshtml
@model FootascrazyCarSales.Models.Enquiry.EnquiryVm

@{ Layout = null; }

@using (Html.BeginForm()){
    
    @Html.ValidationSummary()

    @Html.HiddenFor(m => m.Entity.CarId)

    <fieldset>
        <legend>Make an Enquiry</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Entity.EnquirerName)
                @Html.TextBoxFor(m => m.Entity.EnquirerName)
            </li>
            <li>
                @Html.LabelFor(m => m.Entity.EnquirerEmail)
                @Html.TextBoxFor(m => m.Entity.EnquirerEmail)
            </li>
        </ol>
        <input type="submit" value="Enquire" />
    </fieldset>
    
}

FootascrazyCarSales/Views/Enquiry/EnquirySubmitted.cshtml
@model FootascrazyCarSales.Models.Enquiry.EnquiryVm

@{
    Layout = null;
}

<h2>Enquiry Submitted</h2>

<p>
    Thanks for your enquiry regarding @Model.Entity.CarDescription
    It has been forwarded straight to Footascrazy. We hope to hear more from you!
</p>

FootascrazyCarSales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <img src="~/Content/pix/300x300.jpg" />
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>